### PR TITLE
Change to AGPL

### PR DESCRIPTION
**Pull request by iHiD**
We are changing all tooling to use AGPL instead of MIT to protect ourselves against proprietisation. Please see https://github.com/exercism/exercism/issues/5334 for context.

@umaranis @ErikSchierboom - please can you confirm you are happy as the contributors. Thank you :)

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
I'm happy

**Comment by iHiD** [comment]
@umaranis?

**Comment by ErikSchierboom** [comment]
Bump @umaranis

**Comment by ErikSchierboom** [comment]
@iHiD Can we merge this?

**Pull request merged**
